// Equipment chips shown before "show more"
export const EQUIP_INITIAL = 5;

const UI_LABELS_EN = {
  common: {
    category: 'Category',
    equipment: 'Equipment',
    target: 'Target Muscle',
    search: 'Search exercises…',
    clearAll: 'Clear all',
    more: n => `+${n} more`,
    remaining: n => `${n} remaining`,
    exercises: n => `${n.toLocaleString()} exercises`,
    ofExercises: (t, a) => `${t.toLocaleString()} of ${a.toLocaleString()} exercises`,
    bodyPart: 'Body Part',
    targetMeta: 'Target',
    muscles: 'Muscles',
    primary: 'Primary',
    secondary: 'Secondary',
    instructions: 'Instructions',
    empty: 'No exercises found',
    loading: 'Loading exercises…',
    loadFail: 'Failed to load exercises.',
    catalog: 'Catalog',
    logout: 'Log out',
    myProfile: 'My profile',
    settings: 'Settings',
    accountMenu: 'Account menu',
    comingSoon: 'Coming soon',
    theme: 'Theme',
    loadingFilters: 'Loading filters…',
    goToCatalog: 'Go to Catalog',
    copyLink: 'Copy link',
    linkCopied: 'Copied!',
    navGroupExplore: 'Explore',
  },
  auth: {
    loginTitle: 'Sign in',
    registerTitle: 'Create account',
    firstName: 'First name',
    lastName: 'Last name',
    email: 'Email',
    password: 'Password',
    authRole: 'Account type',
    roleAthlete: 'Athlete',
    roleCoach: 'Coach',
    roleAdmin: 'Admin',
    loginSubmit: 'Sign in',
    registerSubmit: 'Create account',
    createAccount: 'Create account',
    haveAccount: 'Sign in',
    registerOk: 'Account created. Sign in to continue.',
    registerFail: 'Could not create account.',
    loginFail: 'Could not sign in.',
    invalidCredentials: 'Invalid email or password.',
    emailTaken: 'That email is already registered.',
  },
  athlete: {
    myPlan: 'My Plan',
    myTraining: 'Training',
    searchTraining: 'Search your plan…',
    navGroupPlan: 'My plan',
    trainingEmpty: 'No exercises in your plan yet.',
    programBare: 'No sets assigned',
    addToPlan: 'Add to my plan',
    inPlan: 'In your plan',
    addToPlanLogin: 'Sign in to save',
    addToPlanFail: 'Could not add to plan.',
    removeFromPlan: 'Remove from plan',
    removedFromPlan: 'Removed from plan',
    undo: 'Undo',
    removeFromPlanFail: 'Could not remove from plan.',
    editPrescription: 'Edit prescription',
    prescriptionSets: 'Sets',
    prescriptionReps: 'Reps',
    prescriptionRest: 'Rest (sec)',
    prescriptionNotes: 'Notes',
    prescriptionSave: 'Save prescription',
    prescriptionSaveFail: 'Could not save prescription.',
    prescriptionNeedField: 'Fill at least one field.',
    prescriptionRepsFormat: 'Use 6 or 8-12.',
    recommendPlan: 'Recommend training',
    recommendPlanLead: 'Pick a muscle zone and we\'ll build a tailored training plan.',
    recommendPlanLocked: 'Pro feature — upgrade to unlock',
    recommendGetPlan: 'Get training',
    recommendAgain: 'Generate another',
    recommendZone: 'Zone',
    recommendZonePlaceholder: 'Choose a zone…',
    recommendEquipment: 'Equipment',
    recommendEquipmentHint: 'Pick 1 or 2',
    recommendEquipmentMax: 'You can pick up to 2 pieces of equipment.',
    recommendSubmit: 'Generate plan',
    recommendFail: 'Could not generate a plan.',
    coachPlan: 'Coach plan',
    coachPlanEmpty: 'No coach yet',
    coachPlanEmptyLead: 'When a coach assigns you, their plan will show up here. In the meantime, train with your own plan or browse the catalog.',
    coachPlanLead: 'Sessions your coach prepared for you.',
    coachPlanProgramEmpty: 'Your coach is linked, but has not built your plan yet.',
    coachInviteLabel: 'Pending invitation',
    coachInviteBannerRest: 'invites you to be their athlete',
    coachInviteAccept: 'Accept',
    coachInviteReject: 'Decline',
    coachInviteAcceptFail: 'Could not accept the invitation.',
    coachInviteRejectFail: 'Could not decline the invitation.',
    coachInviteQuotaFull: 'This coach has reached their athlete limit.',
  },
    coach: {
    navGroupCoach: 'Coach',
    coachPanel: 'Home',
    coachPanelLead: 'A quick look at your athletes and their plans.',
    coachPanelLoading: 'Loading overview…',
    coachPanelTotalAthletes: 'Total athletes',
    coachPanelWithoutPlan: 'Athletes without a plan',
    coachPanelLoadFail: 'Could not load the overview.',
    coachPanelInvitesTitle: 'Invitations',
    coachPanelInvitesLead: 'History of invites you have sent.',
    coachPanelInvitesFilterAll: 'All',
    coachPanelInvitesFilterPending: 'Pending',
    coachPanelInvitesFilterAccepted: 'Accepted',
    coachPanelInvitesFilterRejected: 'Rejected',
    coachPanelInvitesFilterCancelled: 'Cancelled',
    coachPanelInvitesStatusPending: 'Pending',
    coachPanelInvitesStatusAccepted: 'Accepted',
    coachPanelInvitesStatusRejected: 'Rejected',
    coachPanelInvitesStatusCancelled: 'Cancelled',
    coachPanelInvitesEmpty: 'No invitations yet.',
    coachPanelInvitesEmptyFilter: 'No invitations with this status.',
    coachPanelInvitesLoadMore: 'Load more',
    coachPanelInvitesLoadFail: 'Could not load invitations.',
    coachPanelInvitesInvitedAt: 'Sent',
    coachPanelInvitesRespondedAt: 'Responded',
    coachTemplates: 'Templates',
    coachTemplatesLead: 'Build reusable routines here to assign to your athletes.',
    myStudents: 'My athletes',
    studentsLoadMore: 'Load more',
    studentsSearch: 'Search athletes…',
    studentsDownload: 'Download',
    studentsDownloadAll: 'Download all',
    studentsDownloadAllDisabled: 'No plans to download yet.',
    studentsDownloadPlan: 'Download plan',
    studentsDownloadExcel: 'Excel',
    studentsDownloadPdf: 'PDF',
    studentsDownloadPdfSoon: 'Soon',
    studentsDownloadFail: 'Could not download the plan.',
    studentsDownloadSoon: 'Excel export coming soon.',
    studentsLoading: 'Loading athletes…',
    studentsEmptyTitle: 'No athletes yet',
    studentsEmptyLead: 'Invite an athlete with their exact email. When they accept, they will show up here.',
    studentsSearchEmptyTitle: 'No results',
    studentsSearchEmptyLead: 'No athlete matches that search.',
    studentsNewBadge: 'New',
    studentsSort: 'Sort',
    studentsSortWithoutPlan: 'Without plan first',
    studentsSortWithPlan: 'With plan first',
    addStudent: 'Invite athlete',
    addStudentHint: 'Enter the athlete\'s full email. We don\'t search partial matches.',
    addStudentSubmit: 'Send invitation',
    inviteEmailPlaceholder: 'superAtleta@gmail.com',
    inviteSent: 'Invitation sent',
    inviteNotFound: 'No athlete found with that email.',
    inviteHasCoach: 'This athlete already has a coach.',
    invitePending: 'This athlete already has a pending invitation.',
    inviteQuotaFull: 'Athlete limit reached for your plan. Upgrade to invite more.',
    inviteFail: 'Could not send the invitation.',
    addSession: 'Add session',
    addSessionTitle: 'New session',
    addSessionName: 'Name',
    addSessionHint: 'Name the athlete will see (e.g. Monday, Session 1).',
    addSessionSubmit: 'Create session',
    addSessionNamePlaceholder: 'Session 1',
    addSessionDefault: n => `Session ${n}`,
    sessionsHeading: 'Training plan',
    sessionsEmpty: 'No sessions yet',
    sessionEmptyItems: 'No exercises yet',
    sessionExercisesCount: n => (n === 1 ? '1 exercise' : `${n} exercises`),
    sessionSetsCount: n => (n === 1 ? '1 set' : `${n} sets`),
    sessionExercisesUnit: n => (n === 1 ? 'exercise' : 'exercises'),
    sessionSetsUnit: n => (n === 1 ? 'set' : 'sets'),
    sessionIndex: n => `Session ${n}`,
    sessionEdit: 'Edit session',
    sessionAddExercises: 'Add exercises',
    sessionEditorKicker: 'Session',
    sessionEditorBack: 'My athletes',
    sessionRemoveExercise: 'Remove',
    sessionRemove: 'Remove session',
    sessionRemoveTitleBefore: 'Remove ',
    sessionRemoveTitleAfter: '?',
    sessionRemoveConfirm: 'Changes stay unsaved until you save the plan.',
    sessionRemoveCancel: 'Cancel',
    sessionRemoveConfirmBtn: 'Remove',
    sessionEditExercise: 'Edit',
    sessionAddTo: 'Add to session',
    sessionInSession: 'In session',
    sessionAssignLabel: 'Assigning to session',
    sessionAssignDone: 'Back to editor',
    sessionAssignTo: (sessionName, athleteName) => `${sessionName} · ${athleteName}`,
    saveAthletePlan: 'Save plan',
    savingAthletePlan: 'Saving…',
    athletePlanSaved: 'Plan saved',
    athletePlanUnsaved: 'Unsaved changes',
    athletePlanSaveFail: 'Could not save the plan.',
  },
};

const UI_LABELS_ES = {
  common: {
    category: 'Categoría',
    equipment: 'Equipamiento',
    target: 'Músculo objetivo',
    search: 'Buscar ejercicios…',
    clearAll: 'Limpiar todo',
    more: n => `+${n} más`,
    remaining: n => `${n} restantes`,
    exercises: n => `${n.toLocaleString()} ejercicios`,
    ofExercises: (t, a) => `${t.toLocaleString()} de ${a.toLocaleString()} ejercicios`,
    bodyPart: 'Parte del cuerpo',
    targetMeta: 'Objetivo',
    muscles: 'Músculos',
    primary: 'Primario',
    secondary: 'Secundario',
    instructions: 'Instrucciones',
    empty: 'No se encontraron ejercicios',
    loading: 'Cargando ejercicios…',
    loadFail: 'No se pudieron cargar los ejercicios.',
    catalog: 'Catálogo',
    logout: 'Cerrar sesión',
    myProfile: 'Mi perfil',
    settings: 'Configuración',
    accountMenu: 'Menú de cuenta',
    comingSoon: 'Próximamente',
    theme: 'Tema',
    loadingFilters: 'Cargando filtros…',
    goToCatalog: 'Ir a Catálogo',
    copyLink: 'Copiar enlace',
    linkCopied: 'Copiado!',
    navGroupExplore: 'Explorar',
  },
  auth: {
    loginTitle: 'Iniciar sesión',
    registerTitle: 'Crear cuenta',
    firstName: 'Nombre',
    lastName: 'Apellido',
    email: 'Email',
    password: 'Contraseña',
    authRole: 'Tipo de cuenta',
    roleAthlete: 'Atleta',
    roleCoach: 'Entrenador',
    roleAdmin: 'Admin',
    loginSubmit: 'Entrar',
    registerSubmit: 'Crear cuenta',
    createAccount: 'Crear cuenta',
    haveAccount: 'Iniciar sesión',
    registerOk: 'Cuenta creada. Inicia sesión para continuar.',
    registerFail: 'No se pudo crear la cuenta.',
    loginFail: 'No se pudo iniciar sesión.',
    invalidCredentials: 'Email o contraseña incorrectos.',
    emailTaken: 'Ese email ya está registrado.',
  },
  athlete: {
    myPlan: 'Mi plan',
    myTraining: 'Entrenamiento',
    searchTraining: 'Buscar en tu plan…',
    navGroupPlan: 'Mi plan',
    trainingEmpty: 'Aún no hay ejercicios en tu plan.',
    programBare: 'Sin pauta asignada',
    addToPlan: 'Agregar a mi plan',
    inPlan: 'En tu plan',
    addToPlanLogin: 'Inicia sesión para guardar',
    addToPlanFail: 'No se pudo agregar al plan.',
    removeFromPlan: 'Quitar del plan',
    removedFromPlan: 'Quitado del plan',
    undo: 'Deshacer',
    removeFromPlanFail: 'No se pudo quitar del plan.',
    editPrescription: 'Editar pauta',
    prescriptionSets: 'Series',
    prescriptionReps: 'Reps',
    prescriptionRest: 'Descanso (seg)',
    prescriptionNotes: 'Notas',
    prescriptionSave: 'Guardar pauta',
    prescriptionSaveFail: 'No se pudo guardar la pauta.',
    prescriptionNeedField: 'Completa al menos un campo.',
    prescriptionRepsFormat: 'Usá 6 u 8-12.',
    recommendPlan: 'Recomendar Entrenamiento',
    recommendPlanLead: 'Elige la zona muscular y te armamos un plan de entrenamiento a medida.',
    recommendPlanLocked: 'Función Pro — mejora tu plan para desbloquearla',
    recommendGetPlan: 'Conseguir entrenamiento',
    recommendAgain: 'Generar otro',
    recommendZone: 'Zona',
    recommendZonePlaceholder: 'Elige una zona…',
    recommendEquipment: 'Equipamiento',
    recommendEquipmentHint: 'Elige 1 o 2',
    recommendEquipmentMax: 'Puedes elegir hasta 2 equipamientos.',
    recommendSubmit: 'Generar plan',
    recommendFail: 'No se pudo generar el plan.',
    coachPlan: 'Plan del coach',
    coachPlanEmpty: 'Aún no tienes coach',
    coachPlanEmptyLead: 'Cuando un coach te asigne, aquí verás el plan que preparó para ti. Mientras tanto, entrena con tu plan o explora el catálogo.',
    coachPlanLead: 'Sesiones que tu coach armó para ti.',
    coachPlanProgramEmpty: 'Ya tienes coach, pero todavía no armó tu plan.',
    coachInviteLabel: 'Invitación pendiente',
    coachInviteBannerRest: 'te invita a ser su alumno',
    coachInviteAccept: 'Aceptar',
    coachInviteReject: 'Rechazar',
    coachInviteAcceptFail: 'No se pudo aceptar la invitación.',
    coachInviteRejectFail: 'No se pudo rechazar la invitación.',
    coachInviteQuotaFull: 'Este coach alcanzó su límite de alumnos.',
  },
  coach: {
    navGroupCoach: 'Coach',
    coachPanel: 'Panel',
    coachPanelLead: 'Resumen rápido de tus alumnos y sus pautas.',
    coachPanelLoading: 'Cargando resumen…',
    coachPanelTotalAthletes: 'Total de alumnos',
    coachPanelWithoutPlan: 'Alumnos sin pauta',
    coachPanelLoadFail: 'No se pudo cargar el resumen.',
    coachPanelInvitesTitle: 'Invitaciones',
    coachPanelInvitesLead: 'Historial de invitaciones que enviaste.',
    coachPanelInvitesFilterAll: 'Todas',
    coachPanelInvitesFilterPending: 'Pendientes',
    coachPanelInvitesFilterAccepted: 'Aceptadas',
    coachPanelInvitesFilterRejected: 'Rechazadas',
    coachPanelInvitesFilterCancelled: 'Canceladas',
    coachPanelInvitesStatusPending: 'Pendiente',
    coachPanelInvitesStatusAccepted: 'Aceptada',
    coachPanelInvitesStatusRejected: 'Rechazada',
    coachPanelInvitesStatusCancelled: 'Cancelada',
    coachPanelInvitesEmpty: 'Aún no hay invitaciones.',
    coachPanelInvitesEmptyFilter: 'No hay invitaciones con este estado.',
    coachPanelInvitesLoadMore: 'Cargar más',
    coachPanelInvitesLoadFail: 'No se pudieron cargar las invitaciones.',
    coachPanelInvitesInvitedAt: 'Enviada',
    coachPanelInvitesRespondedAt: 'Respondida',
    coachTemplates: 'Plantillas',
    coachTemplatesLead: 'Acá vas a armar rutinas reutilizables para asignar a tus alumnos.',
    myStudents: 'Mis alumnos',
    studentsLoadMore: 'Cargar más',
    studentsSearch: 'Buscar alumnos…',
    studentsDownload: 'Descargar',
    studentsDownloadAll: 'Descargar todos',
    studentsDownloadAllDisabled: 'Todavía no hay planes para descargar.',
    studentsDownloadPlan: 'Descargar plan',
    studentsDownloadExcel: 'Excel',
    studentsDownloadPdf: 'PDF',
    studentsDownloadPdfSoon: 'Pronto',
    studentsDownloadFail: 'No se pudo descargar el plan.',
    studentsDownloadSoon: 'Pronto podrás exportar a Excel.',
    studentsLoading: 'Cargando alumnos…',
    studentsEmptyTitle: 'Aún no tienes alumnos',
    studentsEmptyLead: 'Invita a un atleta por su email exacto. Cuando acepte, aparecerá acá.',
    studentsSearchEmptyTitle: 'Sin resultados',
    studentsSearchEmptyLead: 'Ningún alumno coincide con esa búsqueda.',
    studentsNewBadge: 'Nuevo',
    studentsSort: 'Ordenar',
    studentsSortWithoutPlan: 'Sin pauta primero',
    studentsSortWithPlan: 'Con pauta primero',
    addStudent: 'Invitar alumno',
    addStudentHint: 'Escribe el email completo del atleta. No buscamos coincidencias parciales.',
    addStudentSubmit: 'Enviar invitación',
    inviteEmailPlaceholder: 'superAtleta@gmail.com',
    inviteSent: 'Invitación enviada',
    inviteNotFound: 'No encontramos un atleta con ese email.',
    inviteHasCoach: 'Este atleta ya tiene un coach.',
    invitePending: 'Este atleta ya tiene una invitación pendiente.',
    inviteQuotaFull: 'Alcanzaste el límite de alumnos de tu plan. Mejora el plan para invitar más.',
    inviteFail: 'No se pudo enviar la invitación.',
    addSession: 'Agregar sesión',
    addSessionTitle: 'Nueva sesión',
    addSessionName: 'Nombre',
    addSessionHint: 'Nombre visible para el atleta (ej. Lunes, Sesión 1).',
    addSessionSubmit: 'Crear sesión',
    addSessionNamePlaceholder: 'Sesión 1',
    addSessionDefault: n => `Sesión ${n}`,
    sessionsHeading: 'Plan de entrenamiento',
    sessionsEmpty: 'Aún no hay sesiones',
    sessionEmptyItems: 'Sin ejercicios aún',
    sessionExercisesCount: n => (n === 1 ? '1 ejercicio' : `${n} ejercicios`),
    sessionSetsCount: n => (n === 1 ? '1 serie' : `${n} series`),
    sessionExercisesUnit: n => (n === 1 ? 'ejercicio' : 'ejercicios'),
    sessionSetsUnit: n => (n === 1 ? 'serie' : 'series'),
    sessionIndex: n => `Sesión ${n}`,
    sessionEdit: 'Editar sesión',
    sessionAddExercises: 'Agregar ejercicios',
    sessionEditorKicker: 'Sesión',
    sessionEditorBack: 'Mis alumnos',
    sessionRemoveExercise: 'Quitar',
    sessionRemove: 'Eliminar sesión',
    sessionRemoveTitleBefore: '¿Eliminar ',
    sessionRemoveTitleAfter: '?',
    sessionRemoveConfirm: 'Los cambios quedan sin guardar hasta que guardes el plan.',
    sessionRemoveCancel: 'Cancelar',
    sessionRemoveConfirmBtn: 'Eliminar',
    sessionEditExercise: 'Editar',
    sessionAddTo: 'Agregar a la sesión',
    sessionInSession: 'En la sesión',
    sessionAssignLabel: 'Asignando a sesión',
    sessionAssignDone: 'Volver al editor',
    sessionAssignTo: (sessionName, athleteName) => `${sessionName} · ${athleteName}`,
    saveAthletePlan: 'Guardar plan',
    savingAthletePlan: 'Guardando…',
    athletePlanSaved: 'Plan guardado',
    athletePlanUnsaved: 'Cambios sin guardar',
    athletePlanSaveFail: 'No se pudo guardar el plan.',
  },
};

// Flat dictionaries — `ui(key)` and data-ui keep working unchanged
export const UI_LABELS = {
  en: {
    ...UI_LABELS_EN.common,
    ...UI_LABELS_EN.auth,
    ...UI_LABELS_EN.athlete,
    ...UI_LABELS_EN.coach,
  },
  es: {
    ...UI_LABELS_ES.common,
    ...UI_LABELS_ES.auth,
    ...UI_LABELS_ES.athlete,
    ...UI_LABELS_ES.coach,
  },
};

// Display labels only — filter keys stay in English (data values)
export const VALUE_LABELS_ES = {
  // category / body_part
  'back': 'Espalda',
  'cardio': 'Cardio',
  'chest': 'Pecho',
  'lower arms': 'Antebrazos',
  'lower legs': 'Pantorrillas',
  'neck': 'Cuello',
  'shoulders': 'Hombros',
  'upper arms': 'Brazos',
  'upper legs': 'Piernas',
  'waist': 'Cintura',
  // equipment
  'assisted': 'Asistido',
  'band': 'Banda elástica',
  'barbell': 'Barra',
  'body weight': 'Peso corporal',
  'bosu ball': 'Bosu',
  'cable': 'Cable',
  'dumbbell': 'Mancuerna',
  'elliptical machine': 'Elíptica',
  'ez barbell': 'Barra EZ',
  'hammer': 'Hammer',
  'kettlebell': 'Pesa rusa',
  'leverage machine': 'Máquina de palanca',
  'medicine ball': 'Balón medicinal',
  'olympic barbell': 'Barra olímpica',
  'resistance band': 'Banda de resistencia',
  'roller': 'Rodillo',
  'rope': 'Cuerda',
  'skierg machine': 'SkiErg',
  'sled machine': 'Trineo de empuje',
  'smith machine': 'Máquina Smith',
  'stability ball': 'Pelota de estabilidad',
  'stationary bike': 'Bicicleta estática',
  'stepmill machine': 'Escaladora',
  'tire': 'Neumático',
  'trap bar': 'Barra hex',
  'upper body ergometer': 'Ergómetro de tren superior',
  'weighted': 'Con peso',
  'wheel roller': 'Rueda abdominal',
  // target + muscles
  'abductors': 'Abductores',
  'abs': 'Abdominales',
  'adductors': 'Aductores',
  'biceps': 'Bíceps',
  'calves': 'Pantorrillas',
  'cardiovascular system': 'Sistema cardiovascular',
  'delts': 'Deltoides',
  'forearms': 'Antebrazos',
  'glutes': 'Glúteos',
  'hamstrings': 'Isquiotibiales',
  'lats': 'Dorsales',
  'levator scapulae': 'Elevador de la escápula',
  'pectorals': 'Pectorales',
  'quads': 'Cuádriceps',
  'serratus anterior': 'Serrato anterior',
  'spine': 'Columna',
  'traps': 'Trapecios',
  'triceps': 'Tríceps',
  'upper back': 'Espalda alta',
  'abdominals': 'Abdominales',
  'ankle stabilizers': 'Estabilizadores del tobillo',
  'ankles': 'Tobillos',
  'brachialis': 'Braquial',
  'core': 'Core',
  'deltoids': 'Deltoides',
  'feet': 'Pies',
  'grip muscles': 'Músculos de agarre',
  'groin': 'Ingle',
  'hands': 'Manos',
  'hip flexors': 'Flexores de cadera',
  'inner thighs': 'Aductores',
  'latissimus dorsi': 'Dorsal ancho',
  'lower abs': 'Abdominales inferiores',
  'lower back': 'Espalda baja',
  'obliques': 'Oblicuos',
  'quadriceps': 'Cuádriceps',
  'rear deltoids': 'Deltoides posteriores',
  'rhomboids': 'Romboides',
  'rotator cuff': 'Manguito rotador',
  'shins': 'Tibial anterior',
  'soleus': 'Sóleo',
  'sternocleidomastoid': 'Esternocleidomastoideo',
  'trapezius': 'Trapecio',
  'upper chest': 'Pectoral superior',
  'wrist extensors': 'Extensores de muñeca',
  'wrist flexors': 'Flexores de muñeca',
  'wrists': 'Muñecas',
};
